import { Telegraf } from 'telegraf';
import { config } from './config.js';
import { startCommand } from './commands/start.js';
import { idCommand, setupOwner } from './commands/owner.js';
import { groupCommand } from './handlers/groups.js';
import { onCallback } from './handlers/callbacks.js';
import { onText } from './handlers/messages.js';
const bot = new Telegraf(config.botToken);
bot.start(async ctx => ctx.chat.type === 'private' ? startCommand(ctx) : groupCommand(ctx));
bot.command('help', async ctx => ctx.chat.type === 'private' ? startCommand(ctx) : groupCommand(ctx));
bot.command('id', idCommand);
bot.command('setup_owner', setupOwner);
bot.on('callback_query', onCallback);
bot.on('text', onText);
bot.catch((err) => console.error('BOT_ERROR', err));
bot.launch();
console.log('TRINTOPE Bot running');
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
